# Run container based
sudo: false

language: java

jdk:
    - oraclejdk8
    - oraclejdk7

env:
    global:
        - DENT_TRAVIS_MVN_SETTINGS_REPO=https://github.com/deventropy/deventropy-parent.git
        # JUNIT_HELPER_COVERALLS_REPO_KEY=<secret...>
        - secure: "ljqZOiitoSOxeZQKbzVo29pXI/7AmJe8niNVTeH0Ty20HNDS03TvxQXAIuRy6Fu2+sfrj0Df6ykLT71SXhAmL/TJjo1JAv+hiV4C8e0ye7O9XvQN6ma0JR5zQZtkZNSgo+eorjLW4IZz/WnSMwXkVHR6Cmx1KnCfoLQZf3HlQ8r0b0HKq6CdG3tGy8A5TJVVMC+udeOI8exG6qRpP7SPtjrsPGMi5gs/xp9aKetO9kES+CCliKoDFTx7fRsC4/ncGn+pTSFsbmvKoVTdVGbMvialPymH59wwdK88FtlCyJHVfJUs8DiMEZI0TDoeMtQgXPMVSdVVaBCAnsONeNAJOYJN9ZMC4oKTp/0B3y9FVbwi11+O01tOQjmOFhrgWTDLDmkQmmlgUIvTZXzl48woVxUtKxqByto0WQUlYuDwXqfCY5u+gV+g33vcw3GI7VtmcFyoIov23MEyeQWEyvjIFS9bdTVQ42ce5NxwIQGOTkejLYL+fEPOX/m4jnKvGpPtsZl2fvrAx3Na6+BfjX6PU2O1c6UbCzckueGoPU33qy8jkADJ9DVFaWu/3qdxEa/gQzkpcpKDe3iPCJOj9dobilBmv65rKz5HplattvghdNrvors0w+mUPa1iZm7+aAEVGys+HJRWL6JbfITbvsdZ4he1UDcmo6+fEjWfoB4U0iA="

# We use JFrog OSS Repository not available in the stock Travis CI environment; so custom settings.xml
# See https://coderwall.com/p/9b_lfq/deploying-maven-artifacts-from-travis

branches:
    except:
        - travis
        - gh-pages

before_install: "git clone -b travis ${DENT_TRAVIS_MVN_SETTINGS_REPO} target/travis"

install: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --settings target/travis/travis-mvn-settings.xml"

script: "mvn test -B --settings target/travis/travis-mvn-settings.xml"

# Coverage report to coveralls.io
after_success:
    - mvn clean test jacoco:report coveralls:report

# Speed up builds
cache:
    directories:
        - $HOME/.m2/repository

before_cache:
    - rm -rf $HOME/.m2/repository/org/deventropy/junit-helper

# Build Notifications (and avoid emails from forks)
# Set the variable DENT_TRAVIS_NOTIFY_EMAIL in the web interface
notifications:
  email:
    recipients:
      - ${DENT_TRAVIS_NOTIFY_EMAIL}
    on_success: always # [always|never|change] default: change
    on_failure: always # [always|never|change] default: always
